#' Calculate Validation Error for Machine Learning Models
#'
#' Computes the validation error for a given machine learning model using resampled datasets.
#' This function fits the model to each split of the data and then collects and filters the performance metrics, specifically focusing on R-squared (rsq) for validation.
#'
#' @param model A machine learning model object, expected to be compatible with the `fit_resamples` method from the `tune` package.
#' @param splits An object containing data splits, typically generated by functions from the
#'        `rsample` package, used for resampling.
#' @param metric The performance metric of interest as a string.
#'
#' @return A data frame containing the R-squared metric for each resample along with an identification of the error type as "Validation".
#'
#' @examples
#' \dontrun{
#' library(dplyr)
#' library(tidymodels) # assuming tidymodels includes necessary packages
#' data(iris)
#' model <- linear_reg() %>% set_engine("lm")
#' splits <- vfold_cv(iris, v = 5)
#' validation_error <- get_validation_error(model, splits)
#' }
#'
#' @export
#' @importFrom dplyr filter select mutate
#' @importFrom tune fit_resamples collect_metrics
#' @importFrom rsample vfold_cv
#' @importFrom rlang .data
#'
#' @seealso \link[tune]{fit_resamples}, \link[tune]{collect_metrics}

get_validation_error <- function(model, splits, metric) {
  # Ensure metric is a string
  if (!is.character(metric)) {
    stop("Error: 'metric' must be a string.")
  }

  results <- model |>
    tune::fit_resamples(splits) |>
    tune::collect_metrics(summarize = FALSE) |>
    dplyr::filter(.data$.metric == metric)

  results |>
    dplyr::select(.data$id, .data$.estimate) |>
    dplyr::mutate(error = "Validation")
}
